# Generated by Django 4.2.2 on 2023-06-09 20:27

from django.db import migrations


class Migration(migrations.Migration):

    def import_initial_leagues(apps, schema_editor):
        if schema_editor.connection.alias != "default":
          return
        League = apps.get_model("myApp", "League")

        # import leage data from initialData/leagues.csv and bulk create League objects
        with open("initialData/leagues.csv") as f:
          league_data = f.read().splitlines()
        league_objects = []
        for line in league_data[1:]:
          id, abbr, name = line.split(",")
          league_objects.append(League(abbr=abbr, name=name))
        League.objects.bulk_create(league_objects)


    dependencies = [
       ("myApp", "0001_initial")
    ]

    operations = [
        migrations.RunPython(import_initial_leagues),
    ]
