# Generated by Django 4.2.2 on 2023-06-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_import_leagues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='abbr',
            field=models.CharField(max_length=3),
        ),
    ]
