# Generated by Django 4.2.2 on 2023-06-09 20:27

from django.db import migrations


class Migration(migrations.Migration):
    def import_initial_teams(apps, schema_editor):
        Team = apps.get_model("myApp", "Team")
        League = apps.get_model("myApp", "League")

        leagues = League.objects.all()
        league_dict = {}
        for league in leagues:
            league_dict[league.abbr] = league

        # import team data from initialData/teams.csv and bulk create Team objects
        with open("initialData/teams.csv") as f:
          team_data = f.read().splitlines()
        team_objects = []
        for line in team_data[1:]:
          abbr, name, league_abbr = line.split(",")
          if league_abbr not in league_dict:
              raise Exception("League with abbreviation %s not found" % league_abbr)
          team_objects.append(Team(abbr=abbr, name=name, league=league_dict[league_abbr]))

        try:
          Team.objects.bulk_create(team_objects)
        except Exception as e:
          print(e)
          raise Exception("Error creating Team objects")


    dependencies = [
       ("myApp", "0003_alter_team_abbr")
    ]

    operations = [
        migrations.RunPython(import_initial_teams),
    ]
